export const APP_TITLE = "Thiago Rodrigues"
export const BASE_URL = "https://blog.thiagorsouza.xyz"
export const AUTHOR = "Thiago Rodrigues"
export const LINKEDIN = "https://linkedin.com/in/thethiago27"
export const GITHUB_URL = "https://github.com/thethiago27"
